### ISSUE TITLE
Extra Links on Website

### ISSUE THREAD

**Issue by Nikki-Luoma** [comptonb37/comptonb37.github.io#1]
In the _config.yml file you still have  "Resources:
                                                         - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
                                                          - Learn markdown: "http://www.markdowntutorial.com/"
                                                          - GitHub Pages: "https://pages.github.com/"
                                                          Author's home: "http://deanattali.com" "
on  your webpage. Since there are not your links I would suggest only having your "about me" bio.

**Comment by comptonb37** [comment]
I believe I have solved this issue so the issue will be closed. Thanks for the feedback!
