### ISSUE TITLE
Commit d71895c 

### ISSUE THREAD

**Issue by BC3410** [comptonb37/comptonb37.github.io#4]
Found this sentence in the 3rd paragraph of your current essay on YouTube: 
“This limits the ability for us gamers to branch out into others genres.”

I suggest “This limits the ability for gamers like me to branch out into other genres.”

Us gamers just sounds weird…might be a Northeastern way of saying it…

**Comment by comptonb37** [comment]
Thanks, I agree with your edit and have implemented it, and thus the issue will be closed
