### ISSUE TITLE
Paragraph 1 suggestions

### ISSUE THREAD

**Issue by geerc** [comptonb37/comptonb37.github.io#7]
Line 2: Consider changing "and branch off of it or copy it completely than to have" to "and branch off of it, or copy it completely, than to have"

Line 4: "his of herself" --> from the beginning pick one of the two and stick with if the entire article. Another option is the use 'one' instead.

Line 4: "limiting his or her" --> _see above_

**Comment by comptonb37** [comment]
Thanks for the feedback, I've edited with regards to your responses. I appreciate it!
