### ISSUE TITLE
Paragraph 2 suggestions

### ISSUE THREAD

**Issue by geerc** [comptonb37/comptonb37.github.io#8]
Line 4: "and been called out for it but I don't believe it's" --> "and been called out for it, but I don't believe it's"

Line 7-8: "Our view on plagiarism must be unanimously against it so that we can start taking action against it" --> I see what you're saying, but I feel it could be stated a little more clearly. One possible suggestion is "Schools must be openly and unanimously against plagiarism, and then we can begin to take action", or something alike.

**Comment by comptonb37** [comment]
Thanks again for the feedback, both issues have been attended to and fixed.
